# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D8iCaDWq8RS1pSWGUnFntNTdWSkvl3Pt
"""

from pathlib import Path
import time
import streamlit as st
import pandas as pd
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.chatbot import Chatbot

BASE_DIR = Path(__file__).resolve().parent.parent
CONF_MATRIX_PATH = BASE_DIR / "results" / "confusion_matrix.png"

st.set_page_config(
    page_title="Academic Chatbot Demo",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------- Styling ----------
st.markdown("""
<style>
.block-container {
    max-width: 1560px;
    padding-top: 1.15rem;
    padding-bottom: 1.4rem;
}

.hero {
    background: linear-gradient(135deg, rgba(59,130,246,0.10), rgba(14,165,233,0.06));
    border: 1px solid rgba(148, 163, 184, 0.22);
    border-radius: 24px;
    padding: 1.15rem 1.2rem 1rem 1.2rem;
    margin-bottom: 1rem;
}

.metric-card {
    background: rgba(100, 116, 139, 0.10);
    border: 1px solid rgba(148, 163, 184, 0.20);
    border-radius: 18px;
    padding: 0.95rem 1rem;
    min-height: 96px;
}

.metric-label {
    font-size: 0.82rem;
    opacity: 0.72;
    margin-bottom: 0.22rem;
}

.metric-value {
    font-size: 1.32rem;
    font-weight: 700;
    line-height: 1.2;
}

.section-title {
    font-size: 1.03rem;
    font-weight: 700;
    margin-bottom: 0.75rem;
}

.soft-label {
    font-size: 0.83rem;
    opacity: 0.74;
    margin-bottom: 0.25rem;
}

.answer-box {
    border: 1px solid rgba(148, 163, 184, 0.18);
    border-radius: 16px;
    padding: 0.8rem 0.9rem;
    background: rgba(100, 116, 139, 0.08);
}

.small-note {
    opacity: 0.72;
    font-size: 0.82rem;
}

.pill {
    display: inline-block;
    padding: 0.28rem 0.62rem;
    border-radius: 999px;
    border: 1px solid rgba(148, 163, 184, 0.18);
    font-size: 0.78rem;
    font-weight: 600;
    margin-right: 0.35rem;
    margin-top: 0.35rem;
    background: rgba(100, 116, 139, 0.08);
}

.empty-panel {
    border: 1px dashed rgba(148, 163, 184, 0.22);
    border-radius: 18px;
    padding: 1rem;
    background: rgba(100, 116, 139, 0.06);
}

hr.soft {
    border: none;
    border-top: 1px solid rgba(148, 163, 184, 0.16);
    margin: 0.8rem 0 1rem 0;
}

div[data-testid="stChatMessage"] {
    border-radius: 18px;
    padding: 0.08rem 0;
}

div[data-testid="stDataFrame"] {
    border-radius: 16px;
    overflow: hidden;
}

div[data-testid="stChatInput"] {
    margin-top: 0.7rem;
}

[data-testid="stSidebar"] {
    border-right: 1px solid rgba(148, 163, 184, 0.12);
}

[data-testid="stSidebar"] .stButton button {
    border-radius: 12px;
    border: 1px solid rgba(148, 163, 184, 0.20);
    padding-top: 0.55rem;
    padding-bottom: 0.55rem;
}

.sidebar-mini-card {
    border: 1px solid rgba(148, 163, 184, 0.18);
    border-radius: 16px;
    padding: 0.8rem 0.85rem;
    background: rgba(100, 116, 139, 0.06);
    margin-bottom: 0.9rem;
}
</style>
""", unsafe_allow_html=True)

# ---------- App state ----------
@st.cache_resource
def load_chatbot():
    return Chatbot()

bot = load_chatbot()

if "messages" not in st.session_state:
    st.session_state.messages = [
        {
            "role": "assistant",
            "query": None,
            "content": (
                "Hello — I’m your academic assistant. "
                "Ask me about the course, grading, instructor, project, or LLM/NLP concepts."
            ),
            "intent": None,
            "retrieved_docs": None,
            "status": "ready",
        }
    ]

if "last_result" not in st.session_state:
    st.session_state.last_result = None

# ---------- Helpers ----------
def classify_status(result: dict) -> str:
    if not result:
        return "Ready"
    if result["intent"] == "oos":
        return "Out of scope"
    if "not confident" in result["response"].lower():
        return "Low confidence"
    return "In scope"

def top_score(result: dict):
    docs = result.get("retrieved_docs") if result else None
    if docs and len(docs) > 0:
        return docs[0]["score"]
    return None

def render_metric_card(label: str, value: str):
    st.markdown(
        f"""
        <div class="metric-card">
            <div class="metric-label">{label}</div>
            <div class="metric-value">{value}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

def run_query(query: str):
    with st.status("Running pipeline...", expanded=True) as status:
        st.write("1. Intent classification")
        time.sleep(0.08)
        result = bot.respond(query)

        st.write("2. Semantic retrieval")
        time.sleep(0.08)

        if result.get("retrieved_docs"):
            st.write("3. Grounded response construction")
        else:
            st.write("3. Fallback response")

        status.update(label="Pipeline complete", state="complete", expanded=False)
    return result

def push_message(role, content, query=None, intent=None, retrieved_docs=None, status="ready"):
    st.session_state.messages.append({
        "role": role,
        "query": query,
        "content": content,
        "intent": intent,
        "retrieved_docs": retrieved_docs,
        "status": status,
    })

def load_metrics_table():
    return pd.DataFrame({
        "Metric": ["Validation Accuracy", "Test Accuracy", "Macro F1", "OOS Recall"],
        "Value": ["0.9357", "0.8857", "0.8820", "0.6000"]
    })

# ---------- Sidebar ----------
with st.sidebar:
    st.title("Demo Controls")
    st.caption("Academic Chatbot")

    st.markdown("""
    <div class="sidebar-mini-card">
        <div style="font-weight:700; margin-bottom:0.35rem;">Quick start</div>
        <div style="font-size:0.84rem; opacity:0.78;">
            Try a course question, a concept question, and an out-of-scope question to inspect different system behaviors.
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("### Suggested queries")
    quick_queries = [
        "What is a transformer?",
        "Who is the instructor?",
        "How is the course graded?",
        "What topics are covered in the course?",
        "Is there a project in this course?",
        "Tell me a joke",
    ]

    for q in quick_queries:
        if st.button(q, use_container_width=True):
            result = run_query(q)
            push_message("user", q, query=q)
            push_message(
                "assistant",
                result["response"],
                query=q,
                intent=result["intent"],
                retrieved_docs=result.get("retrieved_docs"),
                status=classify_status(result),
            )
            st.session_state.last_result = result
            st.rerun()

    st.markdown("---")
    st.markdown("### System")
    st.write("**Intent model:** TF-IDF + Logistic Regression")
    st.write("**Retriever:** Sentence Transformers + cosine similarity")
    st.write("**Generator:** Lightweight grounded response layer")
    st.write("**Corpus:** Course + NLP/LLM knowledge base")

    if st.button("Clear conversation", use_container_width=True):
        st.session_state.messages = [st.session_state.messages[0]]
        st.session_state.last_result = None
        st.rerun()

# ---------- Header ----------
st.markdown("""
<div class="hero">
    <div style="display:flex; justify-content:space-between; gap:1rem; flex-wrap:wrap;">
        <div style="flex:2; min-width:320px;">
            <div style="font-size:1.95rem; font-weight:800; line-height:1.1;">
                🎓 Transformer-Based Academic Chatbot
            </div>
            <div style="margin-top:0.45rem; opacity:0.82;">
                Hybrid NLP pipeline for intent classification, semantic retrieval, and grounded academic response generation.
            </div>
        </div>
        <div style="flex:1; min-width:260px;">
            <div class="answer-box">
                <div class="soft-label">Pipeline</div>
                <div style="font-weight:700;">Query → Intent → Retrieval → Response</div>
                <div class="small-note" style="margin-top:0.4rem;">
                    Retrieved evidence, confidence, and evaluation artifacts are visible in the right panel.
                </div>
            </div>
        </div>
    </div>
</div>
""", unsafe_allow_html=True)

# ---------- Top metrics ----------
result = st.session_state.last_result
intent_value = result["intent"] if result else "—"
score_value = f"{top_score(result):.3f}" if result and top_score(result) is not None else "—"
status_value = classify_status(result)

m1, m2, m3 = st.columns(3)
with m1:
    render_metric_card("Predicted Intent", intent_value)
with m2:
    render_metric_card("Top Retrieval Score", score_value)
with m3:
    render_metric_card("Answer Status", status_value)

st.markdown("<div style='height:0.75rem;'></div>", unsafe_allow_html=True)

# ---------- Main layout ----------
left_col, right_col = st.columns([1.65, 1.0], gap="large")

with left_col:
    st.markdown('<div class="section-title">Conversation</div>', unsafe_allow_html=True)

    chat_box = st.container(border=True)
    with chat_box:
        if len(st.session_state.messages) <= 1:
            st.markdown(
                """
                <div class="empty-panel">
                    Start the conversation with a course-related or concept-related question.
                    You can ask about grading, instructor, project, syllabus, transformers, BERT, RAG, and related NLP topics.
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.markdown("<div style='height:0.8rem;'></div>", unsafe_allow_html=True)

        for msg in st.session_state.messages:
            with st.chat_message(msg["role"]):
                st.markdown(msg["content"])

                if msg["role"] == "assistant" and msg.get("intent"):
                    st.markdown(
                        f"""
                        <span class="pill">Intent: {msg['intent']}</span>
                        <span class="pill">Status: {msg.get('status', 'ready')}</span>
                        """,
                        unsafe_allow_html=True,
                    )

        user_prompt = st.chat_input("Ask a question about the course or LLM/NLP concepts...")

    if user_prompt:
        push_message("user", user_prompt, query=user_prompt)
        result = run_query(user_prompt)
        push_message(
            "assistant",
            result["response"],
            query=user_prompt,
            intent=result["intent"],
            retrieved_docs=result.get("retrieved_docs"),
            status=classify_status(result),
        )
        st.session_state.last_result = result
        st.rerun()

with right_col:
    st.markdown('<div class="section-title">Why this answer?</div>', unsafe_allow_html=True)

    explain_box = st.container(border=True)
    with explain_box:
        if not result:
            st.markdown(
                """
                <div class="empty-panel">
                    Ask a question to inspect intent classification, retrieval confidence,
                    retrieved evidence, and evaluation artifacts.
                </div>
                """,
                unsafe_allow_html=True,
            )
        else:
            score = top_score(result)
            status_now = classify_status(result)

            a, b = st.columns(2)
            with a:
                st.markdown('<div class="soft-label">Predicted intent</div>', unsafe_allow_html=True)
                st.markdown(f"<div class='answer-box'>{result['intent']}</div>", unsafe_allow_html=True)
            with b:
                st.markdown('<div class="soft-label">Status</div>', unsafe_allow_html=True)
                st.markdown(f"<div class='answer-box'>{status_now}</div>", unsafe_allow_html=True)

            st.markdown('<div class="soft-label" style="margin-top:0.8rem;">Final answer</div>', unsafe_allow_html=True)
            st.markdown(f"<div class='answer-box'>{result['response']}</div>", unsafe_allow_html=True)

            if score is not None:
                st.markdown('<div class="soft-label" style="margin-top:0.8rem;">Top retrieval confidence</div>', unsafe_allow_html=True)
                st.progress(min(max(float(score), 0.0), 1.0))
                st.caption(f"Top score: {score:.3f}")

            docs = result.get("retrieved_docs")
            if docs:
                st.markdown("<hr class='soft'>", unsafe_allow_html=True)
                st.markdown('<div class="section-title">Retrieved evidence</div>', unsafe_allow_html=True)

                evidence_df = pd.DataFrame([
                    {
                        "Rank": i + 1,
                        "Topic": d["topic"],
                        "Subtopic": d["subtopic"],
                        "Score": round(d["score"], 4),
                    }
                    for i, d in enumerate(docs)
                ])
                st.dataframe(evidence_df, use_container_width=True, hide_index=True)

                for i, d in enumerate(docs, start=1):
                    with st.expander(f"Document {i} · {d['topic']} · {d['score']:.4f}", expanded=(i == 1)):
                        st.markdown(f"**Subtopic:** {d['subtopic']}")
                        st.markdown(f"**Question variation:** {d['question_variation']}")
                        st.markdown(f"**Answer hint:** {d['answer_hint']}")
                        st.markdown(f"**Context:** {d['context']}")

            st.markdown("<hr class='soft'>", unsafe_allow_html=True)
            st.markdown('<div class="section-title">Interpretation</div>', unsafe_allow_html=True)

            if status_now == "Out of scope":
                st.warning("The query was classified as outside the supported academic scope.")
            elif status_now == "Low confidence":
                st.warning("The query looks relevant, but retrieval confidence is not high enough for a reliable grounded answer.")
            else:
                st.success("The response is grounded in retrieved course knowledge and passed the confidence threshold.")

    st.markdown("<div style='height:0.9rem;'></div>", unsafe_allow_html=True)

    st.markdown('<div class="section-title">Evaluation snapshot</div>', unsafe_allow_html=True)

    eval_box = st.container(border=True)
    with eval_box:
        st.dataframe(load_metrics_table(), use_container_width=True, hide_index=True)

        if CONF_MATRIX_PATH.exists():
            st.markdown('<div class="soft-label" style="margin-top:0.8rem;">Confusion matrix</div>', unsafe_allow_html=True)
            st.image(str(CONF_MATRIX_PATH), width=540)
        else:
            st.info("Confusion matrix image not found in results/.")
