# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D8iCaDWq8RS1pSWGUnFntNTdWSkvl3Pt
"""

from pathlib import Path
import time
import streamlit as st
import pandas as pd

from src.chatbot import Chatbot


st.set_page_config(
    page_title="Academic Chatbot Demo",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------- Styling ----------
st.markdown("""
<style>
.block-container {
    padding-top: 1.5rem;
    padding-bottom: 1.5rem;
    max-width: 1500px;
}

.hero-card {
    background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
    border-radius: 24px;
    padding: 1.5rem 1.5rem 1.25rem 1.5rem;
    color: white;
    border: 1px solid rgba(255,255,255,0.08);
    box-shadow: 0 10px 30px rgba(15, 23, 42, 0.25);
    margin-bottom: 1rem;
}

.hero-subtle {
    color: rgba(255,255,255,0.80);
    font-size: 0.98rem;
}

.metric-card {
    background: #ffffff;
    border: 1px solid rgba(15, 23, 42, 0.08);
    border-radius: 20px;
    padding: 1rem 1rem 0.85rem 1rem;
    box-shadow: 0 6px 20px rgba(15, 23, 42, 0.05);
    min-height: 108px;
}

.metric-label {
    color: #64748b;
    font-size: 0.82rem;
    margin-bottom: 0.35rem;
}

.metric-value {
    color: #0f172a;
    font-size: 1.4rem;
    font-weight: 700;
    line-height: 1.2;
}

.panel-card {
    background: #ffffff;
    border: 1px solid rgba(15, 23, 42, 0.08);
    border-radius: 22px;
    padding: 1rem 1rem 0.5rem 1rem;
    box-shadow: 0 6px 20px rgba(15, 23, 42, 0.05);
}

.section-title {
    font-size: 1.02rem;
    font-weight: 700;
    color: #0f172a;
    margin-bottom: 0.75rem;
}

.soft-label {
    font-size: 0.85rem;
    color: #64748b;
    margin-bottom: 0.25rem;
}

.status-pill {
    display: inline-block;
    padding: 0.35rem 0.7rem;
    border-radius: 999px;
    font-size: 0.82rem;
    font-weight: 600;
    border: 1px solid rgba(15, 23, 42, 0.08);
    background: #f8fafc;
    color: #0f172a;
}

.answer-box {
    background: #f8fafc;
    border: 1px solid rgba(15, 23, 42, 0.08);
    border-radius: 18px;
    padding: 0.9rem 1rem;
    margin-top: 0.4rem;
}

.small-note {
    color: #64748b;
    font-size: 0.82rem;
}

hr.custom-divider {
    border: none;
    border-top: 1px solid rgba(15, 23, 42, 0.08);
    margin: 0.8rem 0 1rem 0;
}
</style>
""", unsafe_allow_html=True)


# ---------- App state ----------
@st.cache_resource
def load_chatbot():
    return Chatbot()

bot = load_chatbot()

if "messages" not in st.session_state:
    st.session_state.messages = [
        {
            "role": "assistant",
            "query": None,
            "content": (
                "Hello — I’m your academic assistant. "
                "Ask me about the course, grading, instructor, project, or LLM/NLP concepts."
            ),
            "intent": None,
            "retrieved_docs": None,
            "status": "ready",
        }
    ]

if "last_result" not in st.session_state:
    st.session_state.last_result = None


# ---------- Helper functions ----------
def classify_status(result: dict) -> str:
    if result["intent"] == "oos":
        return "Out of scope"
    if "not confident" in result["response"].lower():
        return "Low confidence"
    return "In scope"


def top_score(result: dict):
    docs = result.get("retrieved_docs")
    if docs and len(docs) > 0:
        return docs[0]["score"]
    return None


def render_metric_card(label: str, value: str):
    st.markdown(
        f"""
        <div class="metric-card">
            <div class="metric-label">{label}</div>
            <div class="metric-value">{value}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def run_query(query: str):
    with st.status("Running pipeline...", expanded=True) as status:
        st.write("1. Intent classification")
        time.sleep(0.15)
        result = bot.respond(query)

        st.write("2. Semantic retrieval")
        time.sleep(0.15)

        if result.get("retrieved_docs"):
            st.write("3. Grounded response construction")
        else:
            st.write("3. Fallback response")

        status.update(label="Pipeline complete", state="complete", expanded=False)

    return result


def push_message(role, content, query=None, intent=None, retrieved_docs=None, status="ready"):
    st.session_state.messages.append({
        "role": role,
        "query": query,
        "content": content,
        "intent": intent,
        "retrieved_docs": retrieved_docs,
        "status": status,
    })


# ---------- Sidebar ----------
with st.sidebar:
    st.title("Demo Controls")
    st.caption("Transformer-Based Academic Chatbot")

    st.markdown("### Suggested queries")
    quick_queries = [
        "What is a transformer?",
        "Who is the instructor?",
        "How is the course graded?",
        "Is there a project in this course?",
        "What topics are covered in the course?",
        "Tell me a joke",
    ]

    for q in quick_queries:
        if st.button(q, use_container_width=True):
            result = run_query(q)
            push_message("user", q, query=q)
            push_message(
                "assistant",
                result["response"],
                query=q,
                intent=result["intent"],
                retrieved_docs=result.get("retrieved_docs"),
                status=classify_status(result),
            )
            st.session_state.last_result = result
            st.rerun()

    st.markdown("---")
    st.markdown("### System snapshot")
    st.write("**Intent model:** TF-IDF + Logistic Regression")
    st.write("**Retriever:** Sentence-Transformers + cosine similarity")
    st.write("**Generator:** Lightweight grounded response layer")
    st.write("**Knowledge base:** Academic/course-specific corpus")

    st.markdown("### Evaluation snapshot")
    eval_df = pd.DataFrame({
        "Metric": ["Validation Accuracy", "Test Accuracy", "Macro F1", "OOS Recall"],
        "Value": ["0.9357", "0.8857", "0.8820", "0.6000"]
    })
    st.dataframe(eval_df, use_container_width=True, hide_index=True)

    if st.button("Clear conversation", use_container_width=True):
        st.session_state.messages = [st.session_state.messages[0]]
        st.session_state.last_result = None
        st.rerun()


# ---------- Header ----------
st.markdown("""
<div class="hero-card">
    <div style="display:flex; justify-content:space-between; gap:1.2rem; flex-wrap:wrap;">
        <div style="flex:2; min-width: 320px;">
            <div style="font-size:2rem; font-weight:800; line-height:1.15;">
                🎓 Academic Chatbot Demo
            </div>
            <div class="hero-subtle" style="margin-top:0.5rem;">
                A hybrid NLP system that combines intent classification, semantic retrieval,
                and grounded response generation for academic question answering.
            </div>
        </div>
        <div style="flex:1; min-width: 260px;">
            <div style="background: rgba(255,255,255,0.06); border:1px solid rgba(255,255,255,0.08); border-radius:18px; padding:0.9rem 1rem;">
                <div style="font-size:0.8rem; opacity:0.8;">Pipeline</div>
                <div style="font-size:1rem; font-weight:700; margin-top:0.35rem;">
                    Query → Intent → Retrieval → Response
                </div>
                <div class="hero-subtle" style="margin-top:0.5rem;">
                    Explainable by design: retrieved evidence and scores are shown alongside answers.
                </div>
            </div>
        </div>
    </div>
</div>
""", unsafe_allow_html=True)


# ---------- Top metrics ----------
result = st.session_state.last_result
top_intent = result["intent"] if result else "—"
top_score_value = f"{top_score(result):.3f}" if result and top_score(result) is not None else "—"
status_text = classify_status(result) if result else "Ready"

m1, m2, m3 = st.columns(3)
with m1:
    render_metric_card("Predicted Intent", top_intent)
with m2:
    render_metric_card("Top Retrieval Score", top_score_value)
with m3:
    render_metric_card("Answer Status", status_text)

st.markdown("<div style='height: 0.7rem;'></div>", unsafe_allow_html=True)


# ---------- Main layout ----------
left_col, right_col = st.columns([1.55, 1.0], gap="large")

with left_col:
    st.markdown('<div class="panel-card">', unsafe_allow_html=True)
    st.markdown('<div class="section-title">Conversation</div>', unsafe_allow_html=True)

    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

            if msg["role"] == "assistant" and msg.get("intent"):
                st.markdown(
                    f"""
                    <div style="margin-top:0.5rem;">
                        <span class="status-pill">Intent: {msg['intent']}</span>
                        <span class="status-pill" style="margin-left:0.35rem;">Status: {msg.get('status', 'ready')}</span>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )

    user_prompt = st.chat_input("Ask a question about the course or LLM/NLP concepts...")

    if user_prompt:
        push_message("user", user_prompt, query=user_prompt)
        result = run_query(user_prompt)
        push_message(
            "assistant",
            result["response"],
            query=user_prompt,
            intent=result["intent"],
            retrieved_docs=result.get("retrieved_docs"),
            status=classify_status(result),
        )
        st.session_state.last_result = result
        st.rerun()

    st.markdown("</div>", unsafe_allow_html=True)

with right_col:
    st.markdown('<div class="panel-card">', unsafe_allow_html=True)
    st.markdown('<div class="section-title">Why this answer?</div>', unsafe_allow_html=True)

    if not result:
        st.info("Ask a question to inspect the model’s reasoning trail, retrieved evidence, and confidence signals.")
    else:
        score = top_score(result)
        status_now = classify_status(result)

        info_1, info_2 = st.columns(2)
        with info_1:
            st.markdown('<div class="soft-label">Predicted intent</div>', unsafe_allow_html=True)
            st.markdown(f"<div class='answer-box'>{result['intent']}</div>", unsafe_allow_html=True)
        with info_2:
            st.markdown('<div class="soft-label">System status</div>', unsafe_allow_html=True)
            st.markdown(f"<div class='answer-box'>{status_now}</div>", unsafe_allow_html=True)

        st.markdown('<div class="soft-label" style="margin-top:0.8rem;">Final answer</div>', unsafe_allow_html=True)
        st.markdown(f"<div class='answer-box'>{result['response']}</div>", unsafe_allow_html=True)

        if score is not None:
            st.markdown('<div class="soft-label" style="margin-top:0.8rem;">Top retrieval confidence</div>', unsafe_allow_html=True)
            st.progress(min(max(float(score), 0.0), 1.0))
            st.caption(f"Top score: {score:.3f}")

        docs = result.get("retrieved_docs")
        if docs:
            st.markdown("<hr class='custom-divider'>", unsafe_allow_html=True)
            st.markdown('<div class="section-title">Retrieved evidence</div>', unsafe_allow_html=True)

            evidence_df = pd.DataFrame([
                {
                    "Rank": i + 1,
                    "Topic": d["topic"],
                    "Subtopic": d["subtopic"],
                    "Score": round(d["score"], 4),
                }
                for i, d in enumerate(docs)
            ])
            st.dataframe(evidence_df, use_container_width=True, hide_index=True)

            for i, d in enumerate(docs, start=1):
                with st.expander(f"Document {i} · {d['topic']} · score {d['score']:.4f}", expanded=(i == 1)):
                    st.markdown(f"**Subtopic:** {d['subtopic']}")
                    st.markdown(f"**Question variation:** {d['question_variation']}")
                    st.markdown(f"**Answer hint:** {d['answer_hint']}")
                    st.markdown(f"**Context:** {d['context']}")

        st.markdown("<hr class='custom-divider'>", unsafe_allow_html=True)
        st.markdown('<div class="section-title">Interpretation</div>', unsafe_allow_html=True)
        if status_now == "Out of scope":
            st.warning("The query was classified as outside the supported academic scope.")
        elif status_now == "Low confidence":
            st.warning("The query appears academic, but retrieval confidence is not strong enough to support a reliable answer.")
        else:
            st.success("The answer is grounded in the retrieved knowledge base and passed the retrieval confidence threshold.")

    st.markdown("</div>", unsafe_allow_html=True)