# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14qxzbv2EfCYj78ilV-5xVYkvWb1_I2nM
"""

from pathlib import Path
import joblib

from src.preprocess import clean_text
from src.retrieve import Retriever
from src.generate import Generator


BASE_DIR = Path(__file__).resolve().parent.parent
MODEL_PATH = BASE_DIR / "models" / "intent_classifier.pkl"


def rule_based_override(query: str):
    q = query.lower()

    if any(word in q for word in ["joke", "funny", "song", "music", "weather", "traffic", "uber"]):
        return "oos"

    if any(word in q for word in ["instructor", "teacher", "lecturer", "coordinator", "who teaches"]):
        return "agent_identity"

    if any(word in q for word in [
        "grade", "graded", "grading",
        "exam", "final", "midterm",
        "assignment", "project",
        "attendance", "policy"
    ]):
        return "schedule_query"

    if any(word in q for word in [
        "course", "syllabus", "content", "topics", "covered", "curriculum"
    ]):
        return "schedule_query"

    if any(word in q for word in [
        "what is", "explain", "difference between", "bert", "transformer",
        "embedding", "attention", "rag", "fine tuning", "vector database", "llm"
    ]):
        return "concept_query"

    return None


def looks_academic(query: str) -> bool:
    q = query.lower()

    academic_keywords = [
        "course", "syllabus", "instructor", "teacher", "lecturer", "coordinator",
        "grade", "grading", "exam", "final", "midterm", "assignment", "project",
        "attendance", "content", "topic", "bert", "transformer", "embedding",
        "attention", "rag", "fine tuning", "vector database", "llm", "nlp"
    ]

    return any(word in q for word in academic_keywords)


class Chatbot:
    def __init__(self):
        print("Loading intent classifier...")
        self.clf = joblib.load(MODEL_PATH)

        print("Loading retriever...")
        self.retriever = Retriever()

        print("Loading generator...")
        self.generator = Generator()

    def predict_intent(self, query: str):
        query_clean = clean_text(query)
        return self.clf.predict([query_clean])[0]

    def respond(self, query: str):
        override_intent = rule_based_override(query)

        if override_intent is not None:
            intent = override_intent
        else:
            intent = self.predict_intent(query)

        if intent == "oos" and not looks_academic(query):
            return {
                "intent": intent,
                "response": "Sorry, I cannot answer that question."
            }

        if intent == "oos" and looks_academic(query):
            intent = "concept_query"

        docs = self.retriever.retrieve(query, top_k=3, predicted_intent=intent)

        if not docs or docs[0]["score"] < 0.45:
            return {
                "intent": intent,
                "response": "I am not confident that this question is covered by the academic knowledge base.",
                "retrieved_docs": docs
            }

        answer = self.generator.generate_answer(query, docs)

        return {
            "intent": intent,
            "response": answer,
            "retrieved_docs": docs
        }
