# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14qxzbv2EfCYj78ilV-5xVYkvWb1_I2nM
"""

from pathlib import Path
import joblib

from src.preprocess import clean_text
from src.retrieve import Retriever
from src.generate import generate_answer


BASE_DIR = Path(__file__).resolve().parent.parent
MODEL_PATH = BASE_DIR / "models" / "intent_classifier.pkl"


class Chatbot:
    def __init__(self):
        print("Loading intent classifier...")
        self.clf = joblib.load(MODEL_PATH)

        print("Loading retriever...")
        self.retriever = Retriever()

    def predict_intent(self, query: str):
        query_clean = clean_text(query)
        return self.clf.predict([query_clean])[0]

    def respond(self, query: str):
        intent = self.predict_intent(query)

        if intent == "oos":
            return {
                "intent": intent,
                "response": "Sorry, I cannot answer that question."
            }

        docs = self.retriever.retrieve(query, top_k=3, predicted_intent=intent)

        if not docs or docs[0]["score"] < 0.30:
            return {
                "intent": intent,
                "response": "I am not confident that this question is covered by the academic knowledge base.",
                "retrieved_docs": docs
            }

        answer = generate_answer(query, docs)

        return {
            "intent": intent,
            "response": answer,
            "retrieved_docs": docs
        }
