# -*- coding: utf-8 -*-
"""generate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YClK0OfTWRKAr5axxqzmNjPmM-vgjFR4
"""

from typing import List, Dict


def build_prompt(query: str, retrieved_docs: List[Dict]) -> str:
    """
    Create a prompt from retrieved contexts.
    """
    context_block = ""

    for i, doc in enumerate(retrieved_docs):
        context_block += f"{i+1}. {doc['context']}\n"

    prompt = f"""
You are an academic assistant.

Use the following context to answer the question clearly and concisely.

Context:
{context_block}

Question:
{query}

Answer:
"""
    return prompt.strip()


def generate_answer(query: str, retrieved_docs: List[Dict]) -> str:
    """
    Lightweight RAG-style answer generation.
    """
    if not retrieved_docs:
        return "I could not find relevant information."

    best = retrieved_docs[0]
    return f"{best['answer_hint']} (Based on course knowledge.)"
