# -*- coding: utf-8 -*-
"""generate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YClK0OfTWRKAr5axxqzmNjPmM-vgjFR4
"""

from typing import List, Dict



# Query type detection

def detect_query_type(query: str) -> str:
    q = query.lower()

    if "difference" in q or "vs" in q or "compare" in q:
        return "comparison"
    if q.startswith("why") or "why" in q:
        return "why"
    if q.startswith("when") or "which week" in q or "covered" in q:
        return "when"
    if q.startswith("what") or "define" in q or "what are" in q:
        return "definition"

    return "general"



# Scoring function

def score_doc(doc: Dict, query_type: str) -> float:
    text = (
        doc.get("question_variation", "").lower()
        + " "
        + doc.get("context", "").lower()
        + " "
        + doc.get("answer_hint", "").lower()
        + " "
        + doc.get("subtopic", "").lower()
        + " "
        + doc.get("topic", "").lower()
    )

    score = doc["score"]

    # Definition boost
    if query_type == "definition":
        if any(k in text for k in [
            "is a", "refers to", "defined as", "are units", "called tokens"
        ]):
            score += 0.2

    # Why boost
    elif query_type == "why":
        if any(k in text for k in [
            "important", "because", "used for", "helps", "affects", "reason"
        ]):
            score += 0.2

    # When boost (VERY strong)
    elif query_type == "when":
        if any(k in text for k in [
            "week", "covered in week", "taught in week", "schedule"
        ]):
            score += 0.4  # stronger boost

    # Comparison boost
    elif query_type == "comparison":
        if any(k in text for k in [
            "difference", "while", "whereas", "compared"
        ]):
            score += 0.25

    return score


# Reranking

def rerank_docs(query: str, docs: List[Dict]) -> List[Dict]:
    query_type = detect_query_type(query)

    scored = []
    for doc in docs:
        s = score_doc(doc, query_type)
        scored.append((s, doc))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [doc for _, doc in scored]



# Deduplication

def is_redundant(a: str, b: str) -> bool:
    a = a.lower()
    b = b.lower()

    # simple overlap check
    return a in b or b in a


# Answer combination

def combine_answers(query_type: str, docs: List[Dict]) -> str:
    primary = docs[0]["answer_hint"]

    if len(docs) < 2:
        return primary

    secondary = docs[1]["answer_hint"]

    # avoid duplication
    if is_redundant(primary, secondary):
        return primary

    # Definition → keep clean, no merge
    if query_type == "definition":
        return primary

    # Why → enrich slightly
    if query_type == "why":
        return f"{primary} {secondary}"

    # Comparison → combine carefully
    if query_type == "comparison":
        return f"{primary} Additionally, {secondary}"

    # When → only use best (important!)
    if query_type == "when":
        return primary

    return primary


# Main generator

def generate_answer(query: str, retrieved_docs: List[Dict]) -> str:
    if not retrieved_docs:
        return "I could not find relevant information."

    query_type = detect_query_type(query)

    # rerank docs
    docs = rerank_docs(query, retrieved_docs)

    # select / combine
    answer = combine_answers(query_type, docs)

    return f"{answer} (Based on course knowledge.)"
