# -*- coding: utf-8 -*-
"""generate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YClK0OfTWRKAr5axxqzmNjPmM-vgjFR4
"""

# -*- coding: utf-8 -*-
"""generate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YClK0OfTWRKAr5axxqzmNjPmM-vgjFR4
"""

from typing import List, Dict


def detect_query_type(query: str) -> str:
    q = query.lower().strip()

    # overview / broad course coverage
    if any(x in q for x in [
        "what topics are covered",
        "what does the course cover",
        "what topics does the course cover",
        "which topics are included",
        "course cover overall",
        "overall"
    ]):
        return "overview"

    # existence questions
    if any(x in q for x in [
        "is there",
        "does the course have",
        "does it include",
        "is included",
        "does the course include"
    ]):
        return "existence"

    # timing / week questions
    if any(x in q for x in [
        "when", "which week", "what week", "covered in the course", "taught"
    ]):
        return "when"

    # weight / contribution questions
    if any(x in q for x in [
        "how much", "worth", "percentage", "contribution", "weight"
    ]):
        return "weight"

    # comparison questions
    if any(x in q for x in [
        "difference", "vs", "compare"
    ]):
        return "comparison"

    # why questions
    if q.startswith("why") or " why " in q:
        return "why"

    # who questions
    if q.startswith("who") or "instructor" in q or "coordinator" in q:
        return "who"

    # definition questions
    if q.startswith("what") or q.startswith("define") or q.startswith("what are"):
        return "definition"

    return "default"


def score_doc_for_generation(doc: Dict, query_type: str) -> float:
    score = float(doc.get("score", 0.0))
    topic = str(doc.get("topic", "")).lower()
    subtopic = str(doc.get("subtopic", "")).lower()
    qv = str(doc.get("question_variation", "")).lower()
    hint = str(doc.get("answer_hint", "")).lower()
    context = str(doc.get("context", "")).lower()

    text = " ".join([topic, subtopic, qv, hint, context])

    # overview questions should strongly prefer overview-like records
    if query_type == "overview":
        if any(x in subtopic for x in ["overview", "course_content", "content_overview"]):
            score += 0.35
        if any(x in text for x in ["the course covers", "includes", "overall", "topics"]):
            score += 0.20
        if "weekly_schedule" in topic or "week" in subtopic:
            score -= 0.10

    # existence questions should prefer relation / inclusion style records
    elif query_type == "existence":
        if any(x in text for x in ["yes,", "includes", "has a", "has an", "project component", "course includes"]):
            score += 0.25
        if "weight" in subtopic or "weights" in subtopic:
            score -= 0.08

    # week / timing questions
    elif query_type == "when":
        if any(x in subtopic for x in ["timing", "week", "schedule"]):
            score += 0.40
        if any(x in text for x in ["week", "covered in week", "taught in week"]):
            score += 0.25
        if "course_relation" in subtopic:
            score -= 0.10

    # weight / grade contribution questions
    elif query_type == "weight":
        if any(x in subtopic for x in ["weight", "weights", "grading"]):
            score += 0.35
        if any(x in text for x in ["percent", "%", "contributes", "weight"]):
            score += 0.20

    # comparison questions
    elif query_type == "comparison":
        if any(x in text for x in ["difference", "while", "whereas", "compared"]):
            score += 0.30

    # why questions
    elif query_type == "why":
        if any(x in text for x in ["because", "important", "helps", "used for", "matters", "affects"]):
            score += 0.25

    # who questions
    elif query_type == "who":
        if any(x in text for x in ["instructor", "coordinator", "lecturer"]):
            score += 0.30

    # definitions
    elif query_type == "definition":
        if any(x in text for x in ["what is", "what are", "is a", "refers to", "defined as"]):
            score += 0.18

    return score


def rerank_docs_for_generation(query: str, docs: List[Dict]) -> List[Dict]:
    query_type = detect_query_type(query)

    rescored = []
    for doc in docs:
        rescored.append((score_doc_for_generation(doc, query_type), doc))

    rescored.sort(key=lambda x: x[0], reverse=True)
    return [doc for _, doc in rescored]


def deduplicate_hints(hints: List[str]) -> List[str]:
    unique = []
    for h in hints:
        h_clean = h.strip()
        if h_clean and h_clean not in unique:
            unique.append(h_clean)
    return unique


def generate_overview_answer(docs: List[Dict]) -> str:
    # prefer a single clean overview answer if present
    for doc in docs:
        subtopic = str(doc.get("subtopic", "")).lower()
        hint = str(doc.get("answer_hint", "")).strip()
        if subtopic == "overview" and hint:
            return hint

    # fallback: first good answer
    return str(docs[0].get("answer_hint", "")).strip()


def generate_existence_answer(docs: List[Dict], query: str) -> str:
    q = query.lower()

    target_keywords = ["project", "exam", "assignment"]

    matched_keyword = None
    for k in target_keywords:
        if k in q:
            matched_keyword = k
            break

    if matched_keyword is None:
        for doc in docs:
            hint = str(doc.get("answer_hint", "")).strip()
            if hint:
                return hint
        return str(docs[0].get("answer_hint", "")).strip()

    # 1. strongest preference: explicit course_relation / existence style docs
    for doc in docs:
        topic = str(doc.get("topic", "")).lower()
        subtopic = str(doc.get("subtopic", "")).lower()
        qv = str(doc.get("question_variation", "")).lower()
        hint = str(doc.get("answer_hint", "")).strip()

        text = " ".join([
            topic, subtopic, qv,
            str(doc.get("answer_hint", "")),
            str(doc.get("context", ""))
        ]).lower()

        if matched_keyword in text:
            if any(x in subtopic for x in ["course_relation", "existence", "components"]):
                if hint:
                    return hint
            if any(x in qv for x in [
                "is there", "does the course have", "does this course include", "does the course include"
            ]):
                if hint:
                    return hint

    # 2. then prefer direct yes/include/has phrasing
    for doc in docs:
        hint = str(doc.get("answer_hint", "")).strip()
        text = " ".join([
            str(doc.get("topic", "")),
            str(doc.get("subtopic", "")),
            str(doc.get("question_variation", "")),
            str(doc.get("answer_hint", "")),
            str(doc.get("context", "")),
        ]).lower()

        if matched_keyword in text and any(x in text for x in ["yes", "includes", "has a", "has an"]):
            if hint:
                return hint

    # 3. avoid outcomes/objectives as existence answers
    for doc in docs:
        subtopic = str(doc.get("subtopic", "")).lower()
        hint = str(doc.get("answer_hint", "")).strip()
        text = " ".join([
            str(doc.get("topic", "")),
            subtopic,
            str(doc.get("question_variation", "")),
            str(doc.get("answer_hint", "")),
            str(doc.get("context", "")),
        ]).lower()

        if matched_keyword in text and subtopic not in ["outcomes", "objectives", "learning_outcomes"]:
            if hint:
                return hint

    return str(docs[0].get("answer_hint", "")).strip()


def generate_when_answer(docs: List[Dict]) -> str:
    # strongly prefer timing/week records
    for doc in docs:
        subtopic = str(doc.get("subtopic", "")).lower()
        hint = str(doc.get("answer_hint", "")).strip()
        if any(x in subtopic for x in ["timing", "week", "schedule"]) and hint:
            return hint

    return str(docs[0].get("answer_hint", "")).strip()


def generate_weight_answer(docs: List[Dict]) -> str:
    for doc in docs:
        subtopic = str(doc.get("subtopic", "")).lower()
        hint = str(doc.get("answer_hint", "")).strip()
        if any(x in subtopic for x in ["weight", "weights", "grading"]) and hint:
            return hint

    return str(docs[0].get("answer_hint", "")).strip()


def generate_comparison_answer(docs: List[Dict]) -> str:
    hints = deduplicate_hints([str(doc.get("answer_hint", "")).strip() for doc in docs[:3]])
    if len(hints) >= 2:
        return f"{hints[0]} Additionally, {hints[1]}"
    if len(hints) == 1:
        return hints[0]
    return ""


def generate_why_answer(docs: List[Dict]) -> str:
    hints = deduplicate_hints([str(doc.get("answer_hint", "")).strip() for doc in docs[:3]])
    if len(hints) >= 2:
        return f"{hints[0]} {hints[1]}"
    if len(hints) == 1:
        return hints[0]
    return ""


def generate_default_answer(docs: List[Dict]) -> str:
    return str(docs[0].get("answer_hint", "")).strip()


def build_prompt(query: str, retrieved_docs: List[Dict]) -> str:
    """
    Kept for compatibility / documentation, not required by the current generator.
    """
    context_block = ""

    for i, doc in enumerate(retrieved_docs):
        context_block += f"{i+1}. {doc['context']}\n"

    prompt = f"""
You are an academic assistant.

Use the following context to answer the question clearly and concisely.

Context:
{context_block}

Question:
{query}

Answer:
"""
    return prompt.strip()


def generate_answer(query: str, retrieved_docs: List[Dict]) -> str:
    """
    Query-aware grounded answer selection.

    This module:
    - detects the query type
    - reranks retrieved documents
    - selects the most appropriate answer style
    - keeps the response grounded in retrieved evidence
    """
    if not retrieved_docs:
        return "I could not find relevant information."

    query_type = detect_query_type(query)
    docs = rerank_docs_for_generation(query, retrieved_docs)

    if query_type == "overview":
        answer = generate_overview_answer(docs)
    elif query_type == "existence":
        answer = generate_existence_answer(docs, query)
    elif query_type == "when":
        answer = generate_when_answer(docs)
    elif query_type == "weight":
        answer = generate_weight_answer(docs)
    elif query_type == "comparison":
        answer = generate_comparison_answer(docs)
    elif query_type == "why":
        answer = generate_why_answer(docs)
    else:
        answer = generate_default_answer(docs)

    if not answer:
        answer = str(docs[0].get("answer_hint", "")).strip()

    return f"{answer} (Based on course knowledge.)"
