# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GU5i2oaB6oaAiyFL40ZbypLZIKKsybIM
"""

import re
import string

def normalize_whitespace(text: str) -> str:
    """Collapse repeated whitespace into single spaces."""
    return re.sub(r"\s+", " ", text).strip()


def remove_punctuation(text: str) -> str:
    """Remove punctuation characters."""
    return text.translate(str.maketrans("", "", string.punctuation))


def clean_text(text: str) -> str:
    """
    Basic text cleaning for both classifier and retrieval modules.
    """
    if not isinstance(text, str):
        text = str(text)

    text = text.lower()
    text = remove_punctuation(text)
    text = normalize_whitespace(text)
    return text