# -*- coding: utf-8 -*-
"""prepare_clinc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_xaG6vT7v1ZBJqcy58Mv6Yg22G7uPpp
"""

!pip install -q datasets pandas

# Gerekli kütüphaneler:
# - datasets: HuggingFace üzerinden CLINC150 dataset'ini yüklemek için
# - pandas: veriyi DataFrame olarak işlemek için
from datasets import load_dataset
import pandas as pd

# CLINC150 dataset'ini yükle.
# "clinc_oos" veri kümesi, "plus" konfigürasyonu ile çağrılıyor.
# Bu yapı train / validation / test split'lerini içerir.
dataset = load_dataset("clinc_oos", "plus")
dataset

train_df = pd.DataFrame(dataset["train"])
val_df = pd.DataFrame(dataset["validation"])
test_df = pd.DataFrame(dataset["test"])

print(train_df.head())
print(train_df.columns)

# Intent kolonundaki sayısal id'lerin hangi intent adına denk geldiğini al.
# label_names listesinde örneğin 0 -> "restaurant_reviews" gibi bir eşleşme bulunur.

label_feature = dataset["train"].features["intent"]
print(label_feature)
print(label_feature.names[:20])  # ilk 20 intent
print("Toplam intent sayısı:", len(label_feature.names))

print(dataset["train"].features)

intent_names = label_feature.names
for i, name in enumerate(intent_names):
    print(i, name)

train_df = pd.DataFrame(dataset["train"])
val_df = pd.DataFrame(dataset["validation"])
test_df = pd.DataFrame(dataset["test"])

label_names = dataset["train"].features["intent"].names

for df in [train_df, val_df, test_df]:
    df["intent_name"] = df["intent"].apply(lambda x: label_names[x])

# Seçmek istediğimiz intentler ve bunların yeni hedef etiketleri.
# Burada bazı farklı intentler aynı üst etikete map ediliyor.
# Örn:
# - "who_do_you_work_for" ve "what_is_your_name" -> "agent_identity"
# - "reminder" ve "todo_list" -> "task_management"

SELECTED_INTENTS = {
    "definition": "concept_query",
    "translate": "language_assistance",
    "calendar": "schedule_query",
    "schedule_meeting": "scheduling_action",
    "who_do_you_work_for": "agent_identity",
    "what_is_your_name": "agent_identity",
    "reminder": "task_management",
    "todo_list": "task_management",
    "oos": "oos",
}

"""
    Verilen DataFrame içinde sadece seçilen intentleri bırakır
    ve intent adlarını SELECTED_INTENTS mapping'ine göre dönüştürür.

    Girdi kolonları:
    - text
    - intent
    - intent_name

    Çıktı kolonları:
    - text
    - intent   (map edilmiş yeni etiket)
    """

def build_subset(df):
    sub = df[df["intent_name"].isin(SELECTED_INTENTS.keys())].copy()
    sub["intent"] = sub["intent_name"].map(SELECTED_INTENTS)
    return sub[["text", "intent"]].reset_index(drop=True)

train_sub = build_subset(train_df)
val_sub = build_subset(val_df)
test_sub = build_subset(test_df)

"""
    Her intent sınıfından eşit sayıda örnek seçer.

    Parametreler:
    - df: içinde 'intent' kolonu bulunan DataFrame
    - n_per_class: sınıf başına hedef örnek sayısı
    - seed: tekrar üretilebilirlik için random seed

    Not:
    Eğer bir sınıfta yeterli örnek yoksa, mevcut örneklerin tamamı alınır.
    """

def balance_split(df, n_per_class, seed=42):
    parts = []
    for label in sorted(df["intent"].unique()):
        class_df = df[df["intent"] == label]
        sampled = class_df.sample(n=min(n_per_class, len(class_df)), random_state=seed)
        parts.append(sampled)
    out = pd.concat(parts).sample(frac=1, random_state=seed).reset_index(drop=True)
    return out

train_bal = balance_split(train_sub, 100)
val_bal = balance_split(val_sub, 20)
test_bal = balance_split(test_sub, 30)

print("Train:")
print(train_bal["intent"].value_counts())
print("\nValidation:")
print(val_bal["intent"].value_counts())
print("\nTest:")
print(test_bal["intent"].value_counts())

train_bal.to_csv("clinc_subset_train.csv", index=False, encoding="utf-8-sig")
val_bal.to_csv("clinc_subset_val.csv", index=False, encoding="utf-8-sig")
test_bal.to_csv("clinc_subset_test.csv", index=False, encoding="utf-8-sig")