# -*- coding: utf-8 -*-
"""retrieve.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dC6GiFNOrw1DQoSrao8rqYzEwLFQuGuJ
"""

!pip install -q -U sentence-transformers

from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")
print("OK")

!git clone https://github.com/MeowsQueen/Transformer-Based-Academic-Chatbot-with-Intent-Detection-and-RAG-lite-Response-Generation.git

!touch src/__init__.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/Transformer-Based-Academic-Chatbot-with-Intent-Detection-and-RAG-lite-Response-Generation

!pwd
!ls
!ls src

import sys
sys.path.append("/content/Transformer-Based-Academic-Chatbot-with-Intent-Detection-and-RAG-lite-Response-Generation")

import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

from src.preprocess import clean_text


KB_PATH = "data/processed/knowledge_base.csv"
MODEL_NAME = "all-MiniLM-L6-v2"


class Retriever:
    def __init__(self, kb_path=KB_PATH):
        self.kb = pd.read_csv(kb_path)

        # temizle
        self.kb["context"] = self.kb["context"].apply(clean_text)

        # model yükle
        print("Loading embedding model...")
        self.model = SentenceTransformer(MODEL_NAME)

        # embeddingleri hazırla
        print("Encoding knowledge base...")
        self.context_embeddings = self.model.encode(
            self.kb["context"].tolist(),
            show_progress_bar=True
        )

    def retrieve(self, query, top_k=3):
        query = clean_text(query)

        # query embedding
        query_emb = self.model.encode([query])

        # similarity
        scores = cosine_similarity(query_emb, self.context_embeddings)[0]

        # top-k index
        top_idx = np.argsort(scores)[::-1][:top_k]

        results = []
        for idx in top_idx:
            results.append({
                "score": float(scores[idx]),
                "context": self.kb.iloc[idx]["context"],
                "answer_hint": self.kb.iloc[idx]["answer_hint"],
                "topic": self.kb.iloc[idx]["topic"]
            })

        return results

retriever = Retriever()
results = retriever.retrieve("What is a transformer?", top_k=3)

for r in results:
    print("\n---")
    print("Score:", r["score"])
    print("Topic:", r["topic"])
    print("Answer hint:", r["answer_hint"])