# -*- coding: utf-8 -*-
"""retrieve.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16v3orURFwTYao6KUFzhkDNrci0ADlF36
"""

from pathlib import Path
from typing import List, Optional
import re

import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

from src.preprocess import clean_text


BASE_DIR = Path(__file__).resolve().parent.parent
KB_PATH = BASE_DIR / "data" / "processed" / "knowledge_base.csv"
EMBEDDINGS_PATH = BASE_DIR / "models" / "kb_embeddings.npy"
MODEL_NAME = "all-MiniLM-L6-v2"


def tokenize_for_match(text: str):
    return re.findall(r"[a-zA-Z0-9_]+", str(text).lower())


def lexical_bonus(query: str, row) -> float:
    query_tokens = set(tokenize_for_match(query))

    row_text = " ".join([
        str(row.get("topic", "")),
        str(row.get("subtopic", "")),
        str(row.get("question_variation", "")),
        str(row.get("answer_hint", "")),
    ]).lower()

    row_tokens = set(tokenize_for_match(row_text))

    bonus = 0.0

    # exact token overlap
    overlap = query_tokens.intersection(row_tokens)
    bonus += min(len(overlap) * 0.08, 0.24)

    # stronger bonus for short queries like "llm", "mllm", "rag"
    if len(query_tokens) <= 2 and overlap:
        bonus += 0.15

    return bonus


class Retriever:
    def __init__(self, kb_path=KB_PATH, model_name=MODEL_NAME, embeddings_path=EMBEDDINGS_PATH):
        self.kb_path = Path(kb_path)
        self.embeddings_path = Path(embeddings_path)

        self.kb = pd.read_csv(self.kb_path).copy()

        for col in ["question_variation", "context", "answer_hint", "topic", "subtopic"]:
            if col not in self.kb.columns:
                self.kb[col] = ""

        self.kb["question_variation"] = self.kb["question_variation"].fillna("").astype(str)
        self.kb["context"] = self.kb["context"].fillna("").astype(str)
        self.kb["answer_hint"] = self.kb["answer_hint"].fillna("").astype(str)
        self.kb["topic"] = self.kb["topic"].fillna("").astype(str)
        self.kb["subtopic"] = self.kb["subtopic"].fillna("").astype(str)

        # richer retrieval representation
        self.kb["retrieval_text"] = (
            self.kb["question_variation"] + " " +
            self.kb["question_variation"] + " " +
            self.kb["question_variation"] + " " +   # boost question form
            self.kb["subtopic"] + " " +
            self.kb["answer_hint"] + " " +
            self.kb["context"]
        ).apply(clean_text)

        self.model = SentenceTransformer(model_name)
        self.embeddings_path.parent.mkdir(parents=True, exist_ok=True)

        if self.embeddings_path.exists():
            self.embeddings = np.load(self.embeddings_path)

            # if KB changed, rebuild cache
            if len(self.embeddings) != len(self.kb):
                self.embeddings = self.model.encode(
                    self.kb["retrieval_text"].tolist(),
                    show_progress_bar=False
                )
                np.save(self.embeddings_path, self.embeddings)
        else:
            self.embeddings = self.model.encode(
                self.kb["retrieval_text"].tolist(),
                show_progress_bar=False
            )
            np.save(self.embeddings_path, self.embeddings)

    def retrieve(self, query: str, top_k: int = 3, predicted_intent: Optional[str] = None) -> List[dict]:
        query = clean_text(query)

        query_emb = self.model.encode([query])
        semantic_scores = cosine_similarity(query_emb, self.embeddings)[0]

        final_scores = []
        for idx, row in self.kb.iterrows():
            bonus = lexical_bonus(query, row)
            final_scores.append(float(semantic_scores[idx]) + bonus)

        final_scores = np.array(final_scores)
        top_idx = np.argsort(final_scores)[::-1][:top_k]

        results = []
        for idx in top_idx:
            row = self.kb.iloc[idx]
            results.append({
                "score": float(final_scores[idx]),
                "doc_id": row.get("doc_id", ""),
                "topic": row.get("topic", ""),
                "subtopic": row.get("subtopic", ""),
                "question_variation": row.get("question_variation", ""),
                "context": row.get("context", ""),
                "answer_hint": row.get("answer_hint", ""),
            })

        return results
