# -*- coding: utf-8 -*-
"""train_intent_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5YpTubr63LG2o4z38FRD6IV8w0Y4LV1
"""

import os
import joblib
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    ConfusionMatrixDisplay,
)

from preprocess import clean_text

TRAIN_PATH = "data/processed/clinc_subset_train.csv"
VAL_PATH = "data/processed/clinc_subset_val.csv"
TEST_PATH = "data/processed/clinc_subset_test.csv"

RESULTS_DIR = "results"
MODELS_DIR = "models"

MODEL_PATH = os.path.join(MODELS_DIR, "intent_classifier.pkl")
METRICS_PATH = os.path.join(RESULTS_DIR, "metrics.txt")
CONF_MATRIX_PATH = os.path.join(RESULTS_DIR, "confusion_matrix.png")

def ensure_dirs():
    os.makedirs(RESULTS_DIR, exist_ok=True)
    os.makedirs(MODELS_DIR, exist_ok=True)


def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    df = df.dropna(subset=["text", "intent"]).copy()
    df["text"] = df["text"].apply(clean_text)
    return df


def build_pipeline() -> Pipeline:
    pipeline = Pipeline([
        ("tfidf", TfidfVectorizer(ngram_range=(1, 2), min_df=1)),
        ("clf", LogisticRegression(max_iter=1000, random_state=42))
    ])
    return pipeline


def save_metrics(val_df, val_pred, test_df, test_pred):
    val_acc = accuracy_score(val_df["intent"], val_pred)
    test_acc = accuracy_score(test_df["intent"], test_pred)

    val_report = classification_report(val_df["intent"], val_pred, digits=4)
    test_report = classification_report(test_df["intent"], test_pred, digits=4)

    with open(METRICS_PATH, "w", encoding="utf-8") as f:
        f.write("=== Validation Accuracy ===\n")
        f.write(f"{val_acc:.4f}\n\n")

        f.write("=== Test Accuracy ===\n")
        f.write(f"{test_acc:.4f}\n\n")

        f.write("=== Validation Classification Report ===\n")
        f.write(val_report)
        f.write("\n\n")

        f.write("=== Test Classification Report ===\n")
        f.write(test_report)

    print(f"Validation Accuracy: {val_acc:.4f}")
    print(f"Test Accuracy: {test_acc:.4f}")
    print("\nTest Classification Report:\n")
    print(test_report)


def save_confusion_matrix(test_df, test_pred):
    labels = sorted(test_df["intent"].unique())

    fig, ax = plt.subplots(figsize=(8, 8))
    ConfusionMatrixDisplay.from_predictions(
        test_df["intent"],
        test_pred,
        display_labels=labels,
        xticks_rotation=45,
        ax=ax,
    )
    plt.tight_layout()
    plt.savefig(CONF_MATRIX_PATH, dpi=200, bbox_inches="tight")
    plt.close()

def main():
    ensure_dirs()

    train_df = load_data(TRAIN_PATH)
    val_df = load_data(VAL_PATH)
    test_df = load_data(TEST_PATH)

    pipeline = build_pipeline()
    pipeline.fit(train_df["text"], train_df["intent"])

    val_pred = pipeline.predict(val_df["text"])
    test_pred = pipeline.predict(test_df["text"])

    save_metrics(val_df, val_pred, test_df, test_pred)
    save_confusion_matrix(test_df, test_pred)

    joblib.dump(pipeline, MODEL_PATH)
    print(f"\nSaved model to: {MODEL_PATH}")
    print(f"Saved metrics to: {METRICS_PATH}")
    print(f"Saved confusion matrix to: {CONF_MATRIX_PATH}")


if __name__ == "__main__":
    main()